### ISSUE TITLE
Licensing issue

### ISSUE THREAD

**Issue by mlandauer** [OpenAddressesUK/chas#10]
Hi folks,

No doubt this is a simple mistake. The main code for running docker containers in chas is clearly derived from morph.io code which is [licensed under AGPL](https://github.com/openaustralia/morph/blob/master/LICENSE). Having done this you can't relicense chas in its current form under MIT.

It would be great if you could resolve this either by relicensing chas and attributing morph or rewriting any code from scratch that was derived from morph. Thanks!

**Comment by pezholio** [comment]
I am SO sorry. We tend to just apply MIT across the board, and totally forgot to check Morph's license. Have fixed now. Thanks for all the work on Morph - it's a great project! :+1:

**Comment by mlandauer** [comment]
Many thanks @pezholio!
